### ISSUE TITLE
Parent folder cover, or empty folder cover

### ISSUE THREAD

**Issue by Cherryblue** [sentriz/gonic#161]
Hello guys,

I've been using Gonic for more than 2 years now and I really like it :).

Looking back at the "directory structure" mentioned on the github page of Gonic, I can see multiple levels of directories, which kind of matches mine.

For example, my albums are grouped by its artist.

My issue, if any, is that I can't seem to get a cover for the "parent folder", which in my case is the artist folder.
This makes me see a lot of "empty cover folders" when browsing through my library, which I find sad.

Is it possible on Gonic ? If so, does it work ? Maybe it's a front-end bug and not a back-end one, but I need to ask :).
In any case, it doesn't work for me, using Gonic + Jamstash. But maybe this is a Jamstash limitation.

Good day to you all guys !

**Comment by sentriz** [comment]
glad you like gonic :) 

I just tried this with Jamstash and the following structure

```
/music/Test/
/music/Test/folder.jpg
/music/Test/Nested A
/music/Test/Nested A/folder.jpg
/music/Test/Nested A/Nested B
/music/Test/Nested A/Nested B/folder.jpg
/music/Test/Nested A/Nested B/(2002) Dirty Dancing
/music/Test/Nested A/Nested B/(2002) Dirty Dancing/02.10 Buffalo Seven.flac
/music/Test/Nested A/Nested B/(2002) Dirty Dancing/01.10 Make Up Your Mind.flac
/music/Test/Nested A/Nested B/(2002) Dirty Dancing/folder.jpg
/music/Test/Nested A/Nested B/(1988) Newbuild
/music/Test/Nested A/Nested B/(1988) Newbuild/01.07 Sync_Swim.mp3
/music/Test/Nested A/Nested B/(1988) Newbuild/02.07 Flow Coma.mp3
/music/Test/Nested A/Nested B/(1988) Newbuild/folder.jpg
```

Jamstash seems to handle it well 

https://user-images.githubusercontent.com/6832539/137002400-0644cec7-df70-428c-87af-be622b549076.mp4

the only image which doesn't render I suppose is `/music/Test/folder.jpg` since that folder is displayed in the sidebar. 
Is this what you're asking or is there something else?

PS I have Jamstash in folder mode not tag mode I think

**Comment by sentriz** [comment]
has the situation improved with gonic master? or docker nightly?

**Comment by sentriz** [comment]
i think this is fixed in master/nightly. please re-open if not. thanks!
