### ISSUE TITLE
Folder layout requirements unclear

### ISSUE THREAD

**Issue by jgdye** [sentriz/gonic#185]
I'm a little confused on what the required directory structure is.  According to the README, an album must be in a single folder, but according to #89, a folder must contain files from only one album.  What is the actual requirement?  Is it both?  Whatever the requirement, I'm happy to submit a pull request that clarifies the text in the README.

**Comment by sentriz** [comment]
`an album must be in a single folder`, `a folder must contain files from only one album`

to me this means the same thing, maybe the second one is the better way of explaining it, which is to say

```
# don't do this
/a
/a/b
/a/b/c
/a/b/c/e
/a/b/c/e/f
/a/b/c/e/f/album 1 track 1.flac
/a/b/c/e/f/album 1 track 2.flac
/a/b/c/e/f/album 1 track 3.flac
/a/b/c/e/f/album 2 track 1.flac
/a/b/c/e/f/album 2 track 2.flac
/a/b/c/e/f/album 2 track 3.flac

# do this
/a
/a/b
/a/b/c
/a/b/c/e
/a/b/c/e/f
/a/b/c/e/f/g
/a/b/c/e/f/g/album 1 track 1.flac
/a/b/c/e/f/g/album 1 track 2.flac
/a/b/c/e/f/g/album 1 track 3.flac
/a/b/c/e/f/h
/a/b/c/e/f/h/album 2 track 1.flac
/a/b/c/e/f/h/album 2 track 2.flac
/a/b/c/e/f/h/album 2 track 3.flac
```

hope this makes sense and would be happy see a better explanation in the readme

thanks!

**Comment by sentriz** [comment]
yeah

`one album per folder`
`one folder (at the deepest level) per album`

both of these are a must. for your situation are you asking because of multi disc albums? where you may have cd1 and cd2 in different folders?

**Comment by jgdye** [comment]
No, I use disc number tags for that. Your system melds well with my library, I just wanted to know because I assumed if I wasn’t sure what the system was there may be others that also didn’t and had a system where it mattered. Aside from using different folders for different discs (where I assume most would want them to be considered separate albums if they organized their music that way), I could see someone choosing to do this for compilation albums so all of an artist's songs are in the same folder tree.
I’ve submitted a pull request with what seems like clearer language to me, feel free to edit to taste.

**Comment by unhammer** [comment]
As far as I can tell, they also need to have the same album artist, or at least not different artist tags? I had a compilation album, all in one folder, where there were many different artists (like a movie soundtrack), but with no album-artist tag, and gonic just seemed to pick some arbitrary artist and only show the tracks from that one, even though they had the same album tag and were in the same folder. When I added the album-artist tag "Various" to all the tracks, it managed to show all of them. What's the exact rule here? Maybe it should also be added to the README :-)

(Also, would it be possible to WARN in the logs when tracks are ignored due to wrong album/artist?)

**Comment by sentriz** [comment]
thanks @unhammer

yeah ideally all the tracks in the the folder would have the same album artist too, since there should only be one album.
and every track in an album should have the same album artist tag by nature

but I would say that was a bug where gonic wouldn't pickup some tracks if there was no/differing album artist tags

it was fixed already on the master branch in the last week, or if not there then on the develop branch. either way in the next release of gonic, those edgecases should be fixed since the scanner has a lot of tests now :sunglasses:

**Comment by unhammer** [comment]
That's good to hear, thanks!
