### ISSUE TITLE
getIndexes returns album ID and different amount of artists between getIndexes and getArtists

### ISSUE THREAD

**Issue by tobiasger** [sentriz/gonic#210]
When doing a call to the `getIndexes` endpoint, I'm getting **al-XX** instead of **ar-XX** for the artist ID. Is this how it's meant to be?

Also, `getIndexes` seems to return a different list of artists than `getArtists`. First off, the ID is formated as **ar-XX** which is, at least for me, expected. But the amount of artists are different as well. From what I can see, `getIndexes` seems to return more artists while `getArtists` in my case only seems to return artists that are in albums with mixed artists in them.

For example, I have one artist called Mr. Mitch that have an album called "Lazy", where Mr. Mitch is the artist on all tracks. When I call `getArtists`, Mr. Mitch is not in the list. But when doing `getIndexes`, Mr. Mitch is there.

**Comment by sentriz** [comment]
yeah, the reason is that the subsonic api is split into 2 categories of endpoints
https://web.archive.org/web/20210814141412/http://www.subsonic.org/pages/api.jsp


"browse by tags" (including getArtists) and "browse by folder" (including getIndexes)

browse by folder doesn't care much about tags, just just your folder structure. so you won't see an ar-xx ids or any "tag related" ids.

another thing to know is that gonic internally shares a table with "albums" from "browse by tags" and "folder" from "browse by folder". thats why getIndexes returns a list of folders with al-xx ids


hope this makes sense


-----------


as for your issue, if you have an album that contains multiple artists (could be a complilation album or maybe an album mostly by artist A but with some guest tracks by artist B) then I would recommend setting the "ALBUMARTIST" tag. for example it could be "Various Artists" or "Artist A". gonic will read that and display it in getArtists

**Comment by sentriz** [comment]
hope this makes sense but please reopen if not!

**Comment by xxxserxxx** [comment]
Can we reopen this?

My argument is twofold:

1. in gonic, /getIndexes returns a subsonic-response/indexes/index/artist which contains entries that are _not_ artists: it's just the top level file entries, whether they're artists, albums, or random directories that don't even contain music.
2. navidrome builds this list of /.../artists from the metadata -- it includes _only_ artists

According to the [OpenSubsonic API documentation](https://opensubsonic.netlify.app/docs/endpoints/getindexes/) for `getIndexes`, the contents of the "artists" array should contain artists.

**Comment by sentriz** [comment]
how would people browse their music by folder (like the orignal subsonic endpoints, not using tag metadata) if getIndexes reached into metadata and only returned artists?

**Comment by xxxserxxx** [comment]
ok, so I don't know whether gonic claims to be compliant with OpenSubsonic, but that has the best API documentation.

According to the API spec, artist IDs are supposed to match directory IDs. We can see this from induction:

1. [GetMusicDirectory](https://opensubsonic.netlify.app/docs/endpoints/getmusicdirectory/) returns filesystem directories:
  > Returns a listing of all files in a music directory
  > ...
  > id: A string which uniquely identifies the music folder. Obtained by calls to getIndexes or getMusicDirectory.
2. [GetIndexes](https://opensubsonic.netlify.app/docs/endpoints/getindexes/) returns a list of artists, which include their IDs
  > Returns an indexed structure of all artists.

Therefore, artist IDs obtained by `GetIndexes` are expected to be passable to GetMusicDirectory, which returns a filesystem (not metadata) view.

This is how navidrome works; it is not how gonic works. Artist IDs obtained from `GetIndexes` are not compatible with `GetMusicDirectory`.

Frankly, I think the Subsonic API is all a bit of a mess, mixing metadata concepts with directory structure, and only recently breaking these out with the `*3` API calls which explicitly talk about searching metadata vs filesystem. I also tend to agree more with gonic's approach of separating the concepts (and IDs); maybe a user has a folder called "Amy Grant" which -- for whatever reason -- contains only Black Sabbath albums. Regardless, the OpenSubsonic documentation is clear that it expects artist IDs to be interchangeable with directory IDs.

Whether or not I think the spec is well-designed, I believe following it is a requirement, as it's the only way clients can expect to work properly.

I'm currently doing a lot of work on [stmps](https://github.com/spezifisch/stmps), @spezifisch 's fork of stmp; spezifisch uses Navidrome, while I've tended to use gonic, so we get testing on both. There are many assumptions in the original stmp code (probably developed against a different server than gonic) which is frequently biting me, and when I look up how the API spec says it's _supposed_ to work, I'm finding that gonic's behavior isn't matching the spec. Much of what I'm fighting with now is that stmp freely conflates Artists & Albums with Directories, and Entities with **both** of those and Songs. This wouldn't be an issue if the data contained type flags, and it isn't an issue if Artist, Album, and Song IDs are also valid Directory and Entity IDs.

I've submitted a patch or two for gonic in the past, but it's been a long time since I've looked into the code. If I had to suggest an approach, it'd be to handle IDs passed to directory calls by looking for the directory indexes, and if not found, as artist and album indexes, and return all of the contents as if they were virtual filesystem objects. At least then it'd match the spec documentation: IDs retrieved through `GetIndexes` -- which returns Artists -- could be used with `GetMusicDirectory` to fetch both songs by the artist with no metadata-defined albums, and albums by the artist.

**Comment by sentriz** [comment]
>  Artist IDs obtained from GetIndexes are not compatible with GetMusicDirectory.

that's not true. getIndexes returns top level directories ("artists", in gonic they have an al- prefix) they are supposed to be used with getMusicDirectory

try [airsonic-refix](https://github.com/tamland/airsonic-refix) with gonic, click Files and browse

it will do the full getMusicFolders -> getIndexes -> getMusicDirectory flow

**Comment by xxxserxxx** [comment]
The [OpenSubsonic documentation for getIndexes](https://opensubsonic.netlify.app/docs/endpoints/getindexes/) explicitly says

> Returns an indexed structure of all artists.

That's quoted from the OpenSubsonic documentation. So when you say

> that's not true. getIndexes returns top level directories

to what are you referring? Not the documented behavior. And also, not the Navidrome behavior, because IDs returned by `getIndexes` can be passed to `getArtist` to get an artist with the same name and ID as what's returned by `getIndexes`.

**Comment by sentriz** [comment]
navidrome's behaviour isn't correct there, and the OS wording is vague. the term "artist" in Subsonic terms has tradidinally been top level dirs and comes from a time before reaching into track metadata. the browse by folder endpoints should only work on filesystem structure. for gonic and other subsonic servers real artists should come from track metadata. including multivalued tags. with a one to many mapping like that there's no relation to the filesystem

check the original docs

https://web.archive.org/web/20220707025402/https://www.subsonic.org/pages/api.jsp#getArtist

the getArtist endpoint came in version much later than the original browse by folder endpoints
