### ISSUE TITLE
mpv not starting on arm/raspberrypi

### ISSUE THREAD

**Issue by sentriz** [sentriz/gonic#265]
from https://github.com/sentriz/gonic/pull/211#issuecomment-1333596043

@marlop352 :wave:

**Comment by lucat1** [comment]
I'm not too familiar with the codebase but differentiating these two error messages here would help follow the "stack trace" a bit further: https://github.com/sentriz/gonic/blob/6c8f6b32995911d7fa9bda64c3986be66de4d366/server/server.go#L364-L367

**Comment by lucat1** [comment]
I've done some local testing (not on a Pi) and it seems to be as I had thought. If the tmp file is not deleted it the checker assumes a socket has been opened (because it only does a stat to check) and tries to connect. Of course another plausible change could be to actually attempt to connect to it in the socket, but my PR is going to leave most of the code as is and just delete the temporary file, which I believe is what the original implementation was meant to be.

**Comment by marlop352** [comment]
Fix confirmed working on my Pi4
