### ISSUE TITLE
Why subsonic API

### ISSUE THREAD

**Issue by trommegutten** [sentriz/gonic#56]
Hi,

Maybe a stupid question, but I'll ask it anyway.

I'm working with my home multiroom system. I've used moode audio for a while (because of it's ok layout (albums showing and easy connect to radiostations). It's using the mpd platform. I'm not sure why, but I haven't found any apps to have the music offline on my phone. Therefore I've recently installed airsonic, tried to run it in jukebox mode, then tried to connect it to snapcast. I don't like the web layout and I'm not sure if the community is supporting airsonic. Then I found the revel and navidrome projects. Now I stumbled across gonic, it seems like you have a lot of things going. Then to my questions:

Why did you chose the subsonic platform, why not eg. mpd platform?

**Comment by sentriz** [comment]
Hi! not a stupid question at all. Originally I choose subsonic because my server is headless, I only had power and ethernet. so I needed a web only solution. I wasn't too happy subsonic and the alternatives, so I made my own. much like lms, navidrome, revel.
Also, as of about 5 minutes ago, @AlexKraak added jukebox support https://github.com/sentriz/gonic/pull/58
Haven't done much testing yet - but if you decide to give gonic a go with jukebox, let us know how it goes :)

**Comment by trommegutten** [comment]
Hi again,
Thank you for answering !

About a week ago I installed LMS (slimserver) on my FreeBSD server. As client I use a raspberry running picoreplayer, and luckily got a hold of three cheap Logitech Squeezebox Boom and one Logitech Squeezebox Touch. I've ordered HIfiberry amp+ to the pi's for better audio quality. In the meantime I must say that I'm amazed of how great the "system" is working. Every client can play for themselves or as part of a group. I can group/link and unlink speakers easy, all clients play nicely in sync, no lagging or troubles. Both local files and radio streaming is playing nicely. Seems as a really great multiroom audio platform. There is also an iOS app (only one app exists, and I had to pay..) that is working perfect. This "system" seems like a real Sonos competitor.

The downside is no offline syncing to the iOS app and the user interface seems a little old. But again, seems like a great platform "under the hood".

Then back to my question: Have you examined the LMS platform, and if so why not build upon the LMS platform? Does LMS have any technical limitations? Wouldn't it be better to just integrate different users and playlists into the LMS platform?

I've also read a bit about snapcast, where it seems they are rebuilding all the LMS features ... I'd like to ask them the same question: why not the LMS platform?

**Comment by sentriz** [comment]
well I'm glad you've found something that works for you and open source too. 
About building off of lms, I don't think it would make much sense to do for gonic - since they are so similar. I think lms has more features in one way, and gonic has more features another way. lms also has a recommendation system apparently which is very cool. 

But whatever you're happy with will be fine. Personally I started gonic before I saw lms, and probably won't switch anytime soon. And I'm sure the lms author feels the same way vice versa
