### ISSUE TITLE
Feature Request: Export playlists to m3u files

### ISSUE THREAD

**Issue by IUCCA** [sentriz/gonic#66]
With this ability it is possible, to use playlists on devices without subsonic client.

**Comment by sentriz** [comment]
good idea thanks. this will also help with #54 if a backup system is needed

**Comment by helmut72** [comment]
Also miss exporting playlists. This feels like a one way, but no way out.  I can't imagine to create playlists when using Gonic and then everything is lost, if I decide to switch to another Subsonic compatible server or want to use playlists otherwise, for example deleting files from a "delete" playlist.

**Comment by IUCCA** [comment]
I wrote a little python script, which exports the playlists. https://github.com/IUCCA/gonic_playlist_export

**Comment by helmut72** [comment]
Thanks! This ~is~ was the most important missed feature.
